spring:
  datasource:
    url: jdbc:sqlserver://${MSSQL_DB:localhost}:1433;databaseName=advert_db;encrypt=true;TrustServerCertificate=True
    username: sa
    password: Password123!
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver