eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka
server:
  port: 8222
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - DELETE
              - POST
              - PUT
      discovery:
        enabled: true
        locator:
          enabled: true
      routes:
        - id: adverts
          uri: lb://advert-service
          predicates:
            - Path=/api/adverts/**
          filters:
            - AuthenticationFilter
        - id: users
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter
        - id: authenticate
          uri: lb://user-service
          predicates:
            - Path=/api/authenticate/**
          filters:
            - AuthenticationFilter